on: [push]
name: CI
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.2'
          cabal-version: '3.2.0.0'
      - uses: actions/cache@v2
        name: Cache cabal store
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: cabal-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            cabal-${{ runner.os }}-
      - name: Configure
        run: cabal configure --write-ghc-environment-files=always
      - name: Build
        run: cabal build
      - name: Test
        run: cabal test --test-show-details=direct
